import { prisma } from "@/lib/prisma";
import { getContent } from "@/lib/content";
import { buildBrief } from "@/lib/brief";
import { PersonalizedRead } from "@/components/PersonalizedRead";
import { PrintButton } from "@/components/PrintButton";
import { NavButton, Screen } from "@/components/ui";

export const dynamic = "force-dynamic";

export default async function BriefPage({ params }: { params: Promise<{ code: string }> }) {
  const { code } = await params;
  const session = await prisma.session.findUnique({
    where: { code: code.toUpperCase() },
    include: { players: true, completions: true },
  });

  if (!session) {
    return (
      <Screen>
        <p className="py-20 text-center text-ink/50">No challenge found for that code.</p>
      </Screen>
    );
  }

  const brief = buildBrief(session, getContent());
  const c = brief.company;
  const profileChips = [c.industry, c.country, c.sapVersion, c.companySize, c.dataSensitivity].filter(Boolean);

  return (
    <Screen className="max-w-3xl space-y-5">
      <div className="flex items-center justify-between print:hidden">
        <NavButton href={`/dashboard?session=${session.id}`}>← Back</NavButton>
        <PrintButton />
      </div>

      {/* Header */}
      <div className="card p-6 text-center">
        <p className="text-xs font-bold uppercase tracking-widest text-ink/45">Challenge brief</p>
        <h1 className="mt-1 font-display text-3xl font-bold">{c.name}</h1>
        {profileChips.length > 0 && (
          <div className="mt-2 flex flex-wrap justify-center gap-1.5">
            {profileChips.map((chip) => (
              <span key={String(chip)} className="rounded-full bg-ink/5 px-2.5 py-0.5 text-xs text-ink/60">
                {chip}
              </span>
            ))}
          </div>
        )}
        <p className="mt-3 text-sm text-ink/55">
          <span className="font-display text-lg font-bold text-brand">{brief.preparationScore}%</span> preparation ·{" "}
          {brief.participants} participant{brief.participants === 1 ? "" : "s"} ·{" "}
          {brief.departments.length} department{brief.departments.length === 1 ? "" : "s"} active
        </p>
      </div>

      {/* What each department flagged — the unique, captured-data part */}
      <section className="space-y-3">
        <h2 className="px-1 font-display text-sm font-bold uppercase tracking-wide text-ink/45">
          What the team flagged
        </h2>
        {brief.departments.length === 0 ? (
          <p className="px-1 text-sm text-ink/40">No actions completed yet.</p>
        ) : (
          brief.departments.map((d) => (
            <div key={d.name} className="card p-4">
              <div className="flex items-center justify-between">
                <p className="font-display font-semibold" style={{ color: d.color }}>
                  {d.name}
                </p>
                <span className="text-xs text-ink/45">
                  {d.players} player{d.players === 1 ? "" : "s"} · {d.readiness}%
                </span>
              </div>
              {d.signals.length > 0 ? (
                <ul className="mt-2 space-y-1 text-sm text-ink/70">
                  {d.signals.map((s, i) => (
                    <li key={i} className="flex gap-2">
                      <span className="text-ink/30">•</span>
                      {s}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="mt-1 text-sm text-ink/40">Participated; no specific signals captured.</p>
              )}
            </div>
          ))
        )}
      </section>

      {/* The personalized read */}
      <section className="space-y-3">
        <h2 className="px-1 font-display text-sm font-bold uppercase tracking-wide text-ink/45">The read</h2>
        <PersonalizedRead
          companyName={c.name}
          profile={{
            industry: c.industry,
            country: c.country,
            sapVersion: c.sapVersion,
            companySize: c.companySize,
            dataSensitivity: c.dataSensitivity,
          }}
        />
      </section>

      <p className="px-1 text-center text-xs text-ink/40">
        Generated by the Cloud Readiness Challenge · {new Date(brief.generatedAt).toLocaleString()} · This is a starting
        read, not a substitute for SAP&apos;s official Readiness Check.
      </p>
    </Screen>
  );
}
